# Generated by Django 4.2.3 on 2023-07-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Joblist',
        ),
    ]
