# Generated by Django 4.2.3 on 2023-07-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0002_rename_usuario_joblist'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='senha',
            field=models.TextField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
