# Generated by Django 4.2.3 on 2023-07-20 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dash', '0003_joblist_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensao_salarial', models.CharField(choices=[('1', 'Até 1.000'), ('2', 'De 1.000 a 2.000'), ('3', 'De 2.000 a 3.000'), ('4', 'Acima de 3.000')], max_length=1)),
                ('experiencia', models.CharField(choices=[('1', 'Sem Experiência'), ('2', 'Menos de 1 ano'), ('3', '1 a 3 anos'), ('4', '3 a 5 anos'), ('5', 'Mais de 5 anos')], max_length=1)),
                ('escolaridade', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TEC', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('POS', 'Pós / MBA / Mestrado'), ('DOUT', 'Doutorado')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('1', 'Até 1.000'), ('2', 'De 1.000 a 2.000'), ('3', 'De 2.000 a 3.000'), ('4', 'Acima de 3.000')], max_length=1)),
                ('requisitos', models.TextField()),
                ('escolaridade_minima', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('TEC', 'Tecnólogo'), ('ES', 'Ensino Superior'), ('POS', 'Pós / MBA / Mestrado'), ('DOUT', 'Doutorado')], max_length=4)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='app_dash.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Joblist',
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='app_dash.usuario'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='app_dash.vaga'),
        ),
    ]
