# Generated by Django 4.2.3 on 2023-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0007_remove_empresa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
