# Generated by Django 4.2.3 on 2023-07-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0008_empresa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
    ]
