# Generated by Django 4.2.3 on 2023-07-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_dash', '0009_remove_empresa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='usuario',
        ),
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
