# Generated by Django 4.2.3 on 2023-07-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0010_remove_candidato_usuario_candidato_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='user',
        ),
        migrations.AddField(
            model_name='candidato',
            name='perfil',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
