# Generated by Django 4.2.3 on 2023-07-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0012_candidato_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
