# Generated by Django 4.2.3 on 2023-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0014_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='pontuacao_escolaridade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pontuacao_faixa_salarial',
            field=models.IntegerField(default=0),
        ),
    ]
