# Generated by Django 4.2.3 on 2023-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0015_candidato_pontuacao_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='pontuacao_total',
            field=models.IntegerField(default=0),
        ),
    ]
