# Generated by Django 4.2.3 on 2023-07-29 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0025_candidato_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='vaga',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
