# Generated by Django 4.2.3 on 2023-07-29 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0026_remove_candidato_data_criacao_vaga_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='data_candidatura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
